### ISSUE TITLE
Setup Gemnasium

### ISSUE THREAD

**Issue by liveh2o** [mxenabled/mad_rubocop#3]
We should setup [Gemnasium](https://gemnasium.com) for this project so we get notified of changes in Rubocop.

**Comment by ztoolson** [comment]
Does MX already have a user setup for Gemnasium?

**Comment by liveh2o** [comment]
Good question. @mmmries, do you know?

**Comment by mmmries** [comment]
I don't know of any "organization" settings on gemnasium, I've only ever used it for my personal projects. I'll go check.

**Comment by mmmries** [comment]
So the way gemnasium works is that you use oauth to connect your github account and then any projects you have access to you can setup gemnasium for them.

This won't give email alerts to the whole team, but we can go ahead and put the badge on the README and everyone will be able to see if we have gotten behind on any of the upstream dependencies

**Comment by mmmries** [comment]
Fixed in  31e2b18

**Comment by liveh2o** [comment]
:+1:
