### ISSUE TITLE
Possibly disable Style/FrozenStringLiteralComment

### ISSUE THREAD

**Issue by jjcarstens** [mxenabled/mad_rubocop#4]
Looks like `Style/FrozenStringLiteralComment` is a cop enforced for Ruby 2.3+ to prep for Ruby 3.0. In some of the apps, that could cause a problem and require more refactoring to avoid modifying string literals and we may want to disable it for now.

@ztoolson

**Comment by mmmries** [comment]
@jjcarstens can you provide an example (or link) to what types of code it will fail and how it wants you to fix those?

**Comment by liveh2o** [comment]
All this cop does is drop a comment in the top of the file that indicates you want to opt-in this feature: `# frozen_string_literal: true`. The cop only seems to expect this to be added to files that explicitly freeze strings. WyeWorks has a [good writeup](https://wyeworks.com/blog/2015/12/1/immutable-strings-in-ruby-2-dot-3) that summarizes the change.

**Comment by mmmries** [comment]
:+1: I like the idea of starting to opt-in to the new feature for 2.3.0+

Does anyone see any downsides to having rubocop enforce the opt-in for us?

**Comment by liveh2o** [comment]
I also like the idea of opting in early. It's also worth noting that this only affects Ruby 2.3+. JRuby does not support it yet, but I have seem some of the JRuby core discussing the feature, so it is likely coming soon.

**Comment by jarecoo** [comment]
:+1: for opting in

**Comment by ztoolson** [comment]
Since we want to opt in, we don't need to change anything.

**Comment by jjcarstens** [comment]
Remember good specs when this is added to a file/project! That could have saved me.
