### ISSUE TITLE
Should Depend on a specific version of rubocop

### ISSUE THREAD

**Issue by mmmries** [mxenabled/mad_rubocop#5]
When we specify our rubocop dependency as `"rubocop", "~> 0.36"` that will allow bundler to install `0.36`, `0.37`, `0.38`...

Since those minor version updates can have new cops that break a build I think it would be better for us to have each version of this gem depend on `~> 0.36.0`. That will allow bundler to update micro version updates (which should just be bugfixes), but it won't allow a minor version update that would break someone's build.

This will require us to release more frequently in this gem, but I think it would be really nice to avoid confusion in the downstream projects.

**Comment by ztoolson** [comment]
:+1: agree. I meant to do it that way, but must have overlooked that when I released the versions.

**Comment by liveh2o** [comment]
A THOUSAND TIMES YES!!!!!!!

**Comment by mmmries** [comment]
This was totally my bad we are currently specifying `~> 0.36.0` in the gemspec. I thought we were just specifying `~> 0.36` which would have caused problems.

The way it is now should be fine and should never introduce breaking changes without changing the version of `mad_rubocop`.

**Comment by liveh2o** [comment]
![nailed_it](https://cloud.githubusercontent.com/assets/207933/13295637/06ddcdae-dae7-11e5-8ad2-94cee70eea2d.gif)
