### ISSUE TITLE
Upgrade MadRubocop to support RuboCop 0.37

### ISSUE THREAD

**Issue by ztoolson** [mxenabled/mad_rubocop#6]
Currently MadRuboCop supports 0.36 version of RuboCop. Here are the new cops introduces in 0.37:

**0.37.0**
- [#2620](https://github.com/bbatsov/rubocop/pull/2620): New cop `Style/ZeroLengthPredicate` checks for `object.size == 0` and variants, and suggests replacing them with an appropriate `empty?` predicate.
- Add new `Style/SpaceAroundKeyword` cop.
- [#2745](https://github.com/bbatsov/rubocop/pull/2745): New cop `Style/MultilineHashBraceLayout` checks that the closing brace in a hash literal is symmetrical with respect to the opening brace and the hash elements.
- [#2761](https://github.com/bbatsov/rubocop/pull/2761): New cop `Style/MultilineMethodDefinitionBraceLayout` checks that the closing brace in a method definition is symmetrical with respect to the opening brace and the method parameters.
- [#2766](https://github.com/bbatsov/rubocop/pull/2766): New cop `Style/MultilineMethodCallBraceLayout` checks that the closing brace in a method call is symmetrical with respect to the opening brace and the method arguments.

I'm not seeing any cops that we should disable, but I'll open up the discussion. What are your thoughts?

**Comment by ztoolson** [comment]
What the upgrade looks like in `newman`
![screen shot 2016-02-29 at 1 43 29 pm](https://cloud.githubusercontent.com/assets/4131873/13408336/8653b36c-deea-11e5-8970-c5a8019b3590.png)

**Comment by ztoolson** [comment]
//cc @liveh2o @mmmries @film42 @vintagepenguin

**Comment by jarecoo** [comment]
I'm cool with all of these.

**Comment by liveh2o** [comment]
Yeah, those all seem to be in line with our style guide. Let's cut a new version.
