### ISSUE TITLE
RuboCop 0.38

### ISSUE THREAD

**Issue by ztoolson** [mxenabled/mad_rubocop#8]
RuboCop has released version 0.38. :tada: :balloon:  It doesn't look like they introduced any new cops but made some improvements on exiting cops.

**Summary of changes:**
- Style/UnlessElse cop can auto-correct.
- Style/OneLineConditional cop can auto-correct.
- Style/ZeroLengthConditional flags code like `array.length < 1`, `1 > array.length`, and so on.
- Lint/BlockAlignment cop can be configured to be stricter.
- Style/Not is able to autocorrect in cases where parentheses must be added to preserve the meaning of an expression.
- Style/Not auto-corrects comparison expressions by removing not and using the opposite comparison.

**Comment by ryanbjones** [comment]
Do we want to use `Style/ZeroLengthPredicate`?  I personally think sometimes it is useful to use `size > 0` for clarity

**Comment by ztoolson** [comment]
@ryanbjones That cop was introduced in RuboCop 0.37. If you think that it is more useful to use size, you can always just disable the cop for that one line.

**Comment by mmmries** [comment]
I'm :+1: for removing the `Style/ZeroLengthPredicate` cop, but we can discuss that outside the scope of this upgrade. That is a style decision that the team can make on its own.
